# Generated by Django 2.2 on 2020-01-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pv',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='article',
            name='uv',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
